### ISSUE TITLE
DateTimeIndication parse

### ISSUE THREAD

**Issue by K47S** [WoLpH/mt940#39]
Hello I've created a python script which uses the FinTs package.
Last week it worked perfectly. Now today the script crashes with the following output:
```
INFO:mt940.tags.DateTimeIndication:matching`` (10) "1703271108" against "^
    (?P<year>\d{2})
    (?P<month>\d{2})
    (?P<day>\d{2})
    (?P<hour>\d{2})
    (?P<minute>\d{2})\+(?P<offset>\d{4})
    "
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    statement = fintsClient.get_statement(accounts[0], date(2017, 1, 1), date.to
day())
  File "C:\Python\lib\site-packages\fints\client.py", line 84, in get_statement
    statement += mt940_to_array(m.group(2))
  File "C:\Python\lib\site-packages\fints\utils.py", line 7, in mt940_to_array
    return transactions.parse(data)
  File "C:\Python\lib\site-packages\mt940\models.py", line 357, in parse
    tag_dict = tag.parse(self, tag_data)
  File "C:\Python\lib\site-packages\mt940\tags.py", line 70, in parse
    self, value)
RuntimeError: ('Unable to parse "<mt940.tags.DateTimeIndication object at 0x0332
75F0>" from "1703271108"', <mt940.tags.DateTimeIndication object at 0x033275F0>,
 '1703271108')
```
Is this a problem of my bank? Could this be related to the daylight changing on sunday?

**Comment by WoLpH** [comment]
Whether it's a problem of your bank is debatable, some other bank(s) claim that the tag should contain an offset as well. Apparently your bank doesn't offer an offset so we'll simply have to assume it's a UTC timestamp.

Can you test the current development release? It should fix your issue

**Comment by WoLpH** [comment]
Cool :) I've just pushed a new release to pypi. A `pip install -U mt940` should do the trick.
