### ISSUE TITLE
error on import in IDLE3

### ISSUE THREAD

**Issue by zdenop** [WoLpH/mt940#59]
I tried to test mt940 in IDLE and I got error:

>>> import mt940
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import mt940
  File "C:\Program Files\Python36\lib\site-packages\mt_940-4.11.0-py3.6.egg\mt940\__init__.py", line 3, in <module>
    from . import tags
  File "C:\Program Files\Python36\lib\site-packages\mt_940-4.11.0-py3.6.egg\mt940\tags.py", line 45, in <module>
    from . import models
  File "C:\Program Files\Python36\lib\site-packages\mt_940-4.11.0-py3.6.egg\mt940\models.py", line 8, in <module>
    from . import _compat
  File "C:\Program Files\Python36\lib\site-packages\mt_940-4.11.0-py3.6.egg\mt940\_compat.py", line 114, in <module>
    console_encoding = sys.__stdout__.encoding
AttributeError: 'NoneType' object has no attribute 'encoding'

import in script works fine.
IDLE version:
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by WoLpH** [comment]
Apparently Windows GUI apps don't define `__stdout__`: https://docs.python.org/3/library/sys.html#sys.__stdout__

For the time being you can work around the issue like this:
```python
import sys
sys.__stdout__ = sys.stdout
import mt940
```

**Comment by zdenop** [comment]
Thanks. This helped!
